name: Gatsby Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
          access-token: ${{ secrets.ACCESS_TOKEN }}
